package uk.gov.hmcts.reform.iahomeofficeintegrationapi.domain.entities.ccd;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;
import uk.gov.hmcts.reform.iahomeofficeintegrationapi.domain.entities.ccd.field.IdValue;
import uk.gov.hmcts.reform.iahomeofficeintegrationapi.domain.entities.ccd.field.YesOrNo;

import java.util.ArrayList;
import java.util.List;

@SuppressWarnings("unchecked")
class StatutoryTimeFrame24WeeksFieldValueTest {

    private StatutoryTimeframe24Weeks statutoryTimeFrame24WeeksFieldValue;

    @Test
    void has_correct_values() {
        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList = new ArrayList<>();
        historyList.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.YES,
            "Test reason",
            "Test case type",
            "Test user",
            "2024-01-01T10:00:00Z"
        )));

        statutoryTimeFrame24WeeksFieldValue = new StatutoryTimeframe24Weeks(
            YesOrNo.YES,
            historyList
        );
        
        assertEquals(YesOrNo.YES, statutoryTimeFrame24WeeksFieldValue.getCurrentStatusAutoGenerated());
        assertNotNull(statutoryTimeFrame24WeeksFieldValue.getHistory());
        assertEquals(1, statutoryTimeFrame24WeeksFieldValue.getHistory().size());
        
        StatutoryTimeframe24WeeksHistory history = statutoryTimeFrame24WeeksFieldValue.getHistory().get(0).getValue();
        assertEquals(YesOrNo.YES, history.getStatus());
        assertEquals("Test reason", history.getReason());
        assertEquals("Test case type", history.getHomeOfficeCaseType());
        assertEquals("Test user", history.getUser());
        assertEquals("2024-01-01T10:00:00Z", history.getDateTimeAdded());
    }

    @Test
    void should_create_object_with_all_fields() {
        YesOrNo status = YesOrNo.YES;
        String reason = "Test reason";
        String caseType = "Test case type";
        String user = "Test user";
        String dateAdded = "2023-01-01T10:00:00Z";

        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList = new ArrayList<>();
        historyList.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            status, reason, caseType, user, dateAdded
        )));

        StatutoryTimeframe24Weeks fieldValue = new StatutoryTimeframe24Weeks(
            status, historyList
        );

        assertEquals(status, fieldValue.getCurrentStatusAutoGenerated());
        assertNotNull(fieldValue.getHistory());
        assertEquals(1, fieldValue.getHistory().size());
        
        StatutoryTimeframe24WeeksHistory history = fieldValue.getHistory().get(0).getValue();
        assertEquals(status, history.getStatus());
        assertEquals(reason, history.getReason());
        assertEquals(caseType, history.getHomeOfficeCaseType());
        assertEquals(user, history.getUser());
        assertEquals(dateAdded, history.getDateTimeAdded());
    }

    @Test
    void equals_should_return_true_for_same_values() {
        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList1 = new ArrayList<>();
        historyList1.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.YES,
            "Test reason",
            "Test case type",
            "Test user",
            "2024-01-01T10:00:00Z"
        )));

        StatutoryTimeframe24Weeks fieldValue1 = new StatutoryTimeframe24Weeks(
            YesOrNo.YES,
            historyList1
        );

        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList2 = new ArrayList<>();
        historyList2.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.YES,
            "Test reason",
            "Test case type",
            "Test user",
            "2024-01-01T10:00:00Z"
        )));

        StatutoryTimeframe24Weeks fieldValue2 = new StatutoryTimeframe24Weeks(
            YesOrNo.YES,
            historyList2
        );

        assertTrue(fieldValue1.equals(fieldValue2));
    }

    @Test
    void toString_should_return_string_representation() {
        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList = new ArrayList<>();
        historyList.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.YES,
            "Test reason",
            "Test case type",
            "Test user",
            "2024-01-01T10:00:00Z"
        )));

        statutoryTimeFrame24WeeksFieldValue = new StatutoryTimeframe24Weeks(
            YesOrNo.YES,
            historyList
        );

        String result = statutoryTimeFrame24WeeksFieldValue.toString();

        assertNotNull(result);
    }

    @Test
    void should_be_equal_when_all_fields_are_same() {
        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList1 = new ArrayList<>();
        historyList1.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.YES, "reason1", "caseType1", "user1", "2020-06-15T17:35:38Z"
        )));

        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList2 = new ArrayList<>();
        historyList2.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.YES, "reason1", "caseType1", "user1", "2020-06-15T17:35:38Z"
        )));

        StatutoryTimeframe24Weeks value1 = new StatutoryTimeframe24Weeks(YesOrNo.YES, historyList1);
        StatutoryTimeframe24Weeks value2 = new StatutoryTimeframe24Weeks(YesOrNo.YES, historyList2);

        assertEquals(value1, value2);
        assertEquals(value1.hashCode(), value2.hashCode());
    }

    @Test
    void should_not_be_equal_when_fields_differ() {
        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList1 = new ArrayList<>();
        historyList1.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.YES, "reason1", "caseType1", "user1", "2020-06-15T17:35:38Z"
        )));

        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList2 = new ArrayList<>();
        historyList2.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.NO, "reason1", "caseType1", "user1", "2020-06-15T17:35:38Z"
        )));

        StatutoryTimeframe24Weeks value1 = new StatutoryTimeframe24Weeks(YesOrNo.YES, historyList1);
        StatutoryTimeframe24Weeks value2 = new StatutoryTimeframe24Weeks(YesOrNo.NO, historyList2);

        assertNotEquals(value1, value2);
    }

    @Test
    void should_not_be_equal_to_null_or_different_class() {
        List<IdValue<StatutoryTimeframe24WeeksHistory>> historyList = new ArrayList<>();
        historyList.add(new IdValue<>("1", new StatutoryTimeframe24WeeksHistory(
            YesOrNo.YES, "reason1", "caseType1", "user1", "2020-06-15T17:35:38Z"
        )));

        StatutoryTimeframe24Weeks value = new StatutoryTimeframe24Weeks(YesOrNo.YES, historyList);

        assertNotEquals(value, null);
        assertNotEquals(value, "string");
    }
}
