targetInstance: ${TEST_URL:http://localhost:8094}

idam:
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  scope: "openid profile roles"

launchDarkly:
  sdkKey: ${LAUNCH_DARKLY_SDK_KEY:sdk-key}
  connectionTimeout: 5000
  socketTimeout: 5000

spring:
  cache:
    cache-names: userInfoCache, legalRepATokenCache, caseOfficerTokenCache, adminOfficerTokenCache, homeOfficePouTokenCache, homeOfficeGenericTokenCache, judgeTokenCache
    caffeine:
      spec: expireAfterAccess=3600s