version: '2.1'

services:
  ia-home-office-integration-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/ia-home-office-integration-api
    container_name: ia-home-office-integration-api
    environment:
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false

    external_links:
      - idam-api
      - dm-store
      - service-auth-provider-api
      - ccd-data-store-api
    ports:
      - ${SERVER_PORT:-8094}:${SERVER_PORT:-8094}
networks:
  compose_default:
    external: true
