java:
  image: 'https://hmctspublic.azurecr.io/ia/homeoffice-integration-api:latest'
  applicationPort: 8098
  aadIdentityName: ia
  environment:
    IDAM_URL: "http://idam-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    ia:
      secrets:
        - system-username
        - system-password
        - idam-client-id
        - idam-secret
        - idam-redirect-uri
        - s2s-secret
        - s2s-microservice
        - idam-url
        - s2s-url
        - AppInsightsInstrumentationKey
