java:
  applicationPort: 8094
  image: 'https://hmctspublic.azurecr.io/ia/homeoffice-integration-api:latest'
  aadIdentityName: ia
  ingressHost: ia-home-office-integration-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    HOME_OFFICE_ENDPOINT: "http://ia-home-office-mock-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - idam-client-id
        - idam-secret
        - s2s-secret
        - s2s-microservice
        - homeoffice-client-id
        - homeoffice-secret
        - AppInsightsInstrumentationKey
