java:
  applicationPort: 8094
  image: 'https://hmctspublic.azurecr.io/ia/homeoffice-integration-api:latest'
  aadIdentityName: ia
  environment:
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    HOME_OFFICE_ENDPOINT: "https://cts-challenge.prp1.np.immigration-api.homeoffice.gov.uk"
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - idam-client-id
        - idam-secret
        - s2s-secret
        - s2s-microservice
        - homeoffice-client-id
        - homeoffice-secret
        - AppInsightsInstrumentationKey
