java:
  applicationPort: 8094
  image: 'https://hmctspublic.azurecr.io/ia/homeoffice-integration-api:latest'
  aadIdentityName: ia
  ingressHost: ia-home-office-integration-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    HOME_OFFICE_ENDPOINT: "http://ia-home-office-mock-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    ROLE_ASSIGNMENT_URL: "http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - name: idam-client-id
          alias: IA_IDAM_CLIENT_ID
        - name: idam-secret
          alias: IA_IDAM_SECRET
        - name: s2s-secret
          alias: IA_S2S_SECRET
        - name: s2s-microservice
          alias: IA_S2S_MICROSERVICE
        - name: homeoffice-client-id
          alias: IA_HOMEOFFICE_CLIENT_ID
        - name: homeoffice-secret
          alias: IA_HOMEOFFICE_SECRET
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: launch-darkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: app-insights-connection-string
          alias: app-insights-connection-string

