java:
  # Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    HOME_OFFICE_ENDPOINT: "https://ia-home-office-mock-api-pr-165.preview.platform.hmcts.net"
    APP_PUBLIC_IP_ENABLED: "true"
    LOGGING_LEVEL_IO_LETTUCE_CORE_PROTOCOL_CONNECTIONWATCHDOG: "WARN" # Suppress the Redis reconnection INFO messages every ten minutes due to no traffic