java:
  applicationPort: 8094
  image: 'https://hmctspublic.azurecr.io/ia/homeoffice-integration-api:latest'
  aadIdentityName: ia
  environment:
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    HOME_OFFICE_ENDPOINT: "http://ia-home-office-mock-api-aat.service.core-compute-aat.internal"
    HOME_OFFICE_CASE_SEARCH_URI: "/v1/applicationStatus/getBySearchParameters"
    HOME_OFFICE_INSTRUCT_URI: "/v1/applicationInstruct/setInstruct"
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - idam-client-id
        - idam-secret
        - s2s-secret
        - s2s-microservice
        - AppInsightsInstrumentationKey
